name: CRON

on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch:

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to google.com
        run: |
          curl \ 
            -X POST "${{ secrets.STAGING_CRON_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"secret\": \"${{ secrets.CRON_SECRET }}\"}"