name: CRON

on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch:

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to google.com
        run: |
          response=$(curl -s -w "\nHTTP_CODE:%{http_code}" "${{ secrets.STAGING_CRON_URL }}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"secret\": \"${{ secrets.CRON_SECRET }}\"}")
          echo "Response:"
          echo "$response"